version: '3'
services: 
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes: 
      - /app/node_modules
      - .:/app
      # for windows containers not detecting changes in react
    environment: 
      - CHOKIDAR_USEPOLLING=true
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - .:/app
      # for windows containers not detecting changes in react
    environment: 
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "test"]
